import type { Artist, ArtistSubmission } from "./types"

export const mockArtists: Artist[] = [
  {
    id: 1,
    name: "Aarav Sharma",
    category: "Singer",
    location: "Mumbai, Maharashtra",
    rating: 4.9,
    reviews: 45,
    priceRange: "₹40,000-80,000",
    image: "/img/Singer.jpg",
    bio: "Professional jazz and pop singer with over 8 years of experience performing at weddings, corporate events, and private parties. Known for my soulful voice and ability to connect with audiences.",
    specialties: ["Jazz", "Pop", "Soul", "Wedding Songs"],
    verified: true,
    responseTime: "2 hours",
    languages: ["English", "Hindi"],
    experience: "Advanced (5-10 years)",
  },
  {
    id: 2,
    name: "Priya Nair",
    category: "Dancer",
    location: "Bengaluru, Karnataka",
    rating: 4.8,
    reviews: 32,
    priceRange: "₹65,000-1,20,000",
    image: "/img/Dancer.jpg",
    bio: "High-energy dance crew specializing in contemporary fusion, hip-hop, and street dance. Perfect for corporate events, festivals, and entertainment shows.",
    specialties: ["Bharatanatyam", "Contemporary", "Folk"],
    verified: true,
    responseTime: "4 hours",
    languages: ["English", "Kannada", "Hindi"],
    experience: "Expert (10+ years)",
  },
  {
    id: 3,
    name: "Rahul Verma",
    category: "DJ",
    location: "Goa, Goa",
    rating: 4.9,
    reviews: 67,
    priceRange: "₹30,000-65,000",
    image: "/img/DJ.jpg",
    bio: "Professional DJ with extensive experience in weddings, corporate events, and nightclub performances. Specializing in electronic, house, and top 40 hits.",
    specialties: ["Electronic", "House", "Wedding", "Top 40"],
    verified: true,
    responseTime: "1 hour",
    languages: ["English", "Hindi"],
    experience: "Advanced (5-10 years)",
  },
  {
    id: 4,
    name: "Aisha Singh",
    category: "Model",
    location: "Delhi, Delhi",
    rating: 4.7,
    reviews: 28,
    priceRange: "₹80,000-1,60,000",
    image: "/img/WomenModel.jpg",
    bio: "Motivational speaker and business coach with 12 years of experience. Specializes in leadership development, team building, and personal growth seminars.",
    specialties: ["Motivational", "Leadership", "Business", "Team Building"],
    verified: true,
    responseTime: "6 hours",
    languages: ["English", "Hindi"],
    experience: "Expert (10+ years)",
  },
  {
    id: 5,
    name: "The Jazz Quartet India",
    category: "Band",
    location: "Kolkata, West Bengal",
    rating: 4.8,
    reviews: 41,
    priceRange: "₹80,000-1,60,000",
    image: "/img/Band.jpg",
    bio: "Professional jazz quartet featuring piano, bass, drums, and saxophone. Perfect for upscale events, cocktail parties, and intimate gatherings.",
    specialties: ["Jazz", "Swing", "Blues", "Cocktail Music"],
    verified: true,
    responseTime: "3 hours",
    languages: ["English", "Bengali", "Hindi"],
    experience: "Expert (10+ years)",
  },
  {
    id: 6,
    name: "Suresh Menon",
    category: "Comedian",
    location: "Ahmedabad, Gujarat",
    rating: 4.6,
    reviews: 53,
    priceRange: "₹40,000-80,000",
    image: "/img/StandUp.jpg",
    bio: "Stand-up comedian with clean, family-friendly humor. Perfect for corporate events, private parties, and entertainment shows.",
    specialties: ["Stand-up", "Clean Comedy", "Corporate", "Improv"],
    verified: false,
    responseTime: "5 hours",
    languages: ["English", "Gujarati", "Hindi"],
    experience: "Advanced (5-10 years)",
  },
  {
    id: 7,
    name: "Elina Reddy",
    category: "Singer",
    location: "Hyderabad, Telangana",
    rating: 4.9,
    reviews: 38,
    priceRange: "₹30,000-65,000",
    image: "/img/WomenSinger.jpg",
    bio: "Bilingual singer specializing in Indian classical, pop, and acoustic performances. Available for weddings, festivals, and cultural events.",
    specialties: ["Classical", "Pop", "Acoustic", "Bilingual"],
    verified: true,
    responseTime: "2 hours",
    languages: ["English", "Telugu", "Hindi"],
    experience: "Intermediate (2-5 years)",
  },
  {
    id: 8,
    name: "Rangilo Rajasthan",
    category: "Band",
    location: "Chennai, Tamil Nadu",
    rating: 4.8,
    reviews: 29,
    priceRange: "₹65,000-1,20,000",
    image: "/img/ClassicalBand.jpg",
    bio: "Professional string quartet and ensemble for weddings, galas, and formal events. Repertoire includes classical, contemporary, and custom arrangements.",
    specialties: ["Classical", "Wedding", "Chamber Music", "Contemporary"],
    verified: true,
    responseTime: "4 hours",
    languages: ["English", "Tamil", "Hindi"],
    experience: "Expert (10+ years)",
  },
]

export const mockArtistSubmissions: ArtistSubmission[] = [
  {
    id: 1,
    name: "Aarav Sharma",
    email: "aarav.sharma@email.com",
    category: "Singer",
    location: "Mumbai, Maharashtra",
    feeRange: "₹40,000-80,000",
    status: "approved",
    rating: 4.9,
    image: "/img/Singer.jpg",
    submittedAt: "2024-01-15",
  },
  {
    id: 2,
    name: "Priya Nair",
    email: "priya.nair@email.com",
    category: "Dancer",
    location: "Bengaluru, Karnataka",
    feeRange: "₹65,000-1,20,000",
    status: "approved",
    rating: 4.8,
    image: "/img/Dancer.jpg",
    submittedAt: "2024-01-18",
  },
  {
    id: 3,
    name: "Rahul Verma",
    email: "rahul.verma@email.com",
    category: "DJ",
    location: "Goa, Goa",
    feeRange: "₹30,000-65,000",
    status: "pending",
    rating: 4.9,
    image: "/img/DJ.jpg",
    submittedAt: "2024-01-20",
  },
  {
    id: 4,
    name: "Aisha Singh",
    email: "aisha.singh@email.com",
    category: "Model",
    location: "Delhi, Delhi",
    feeRange: "₹80,000-1,60,000",
    status: "rejected",
    rating: 4.7,
    image: "/img/WomenModel.jpg",
    submittedAt: "2024-01-12",
  },
  {
    id: 5,
    name: "The Jazz Quartet India",
    email: "jazz.quartet@email.com",
    category: "Band",
    location: "Kolkata, West Bengal",
    feeRange: "₹80,000-1,60,000",
    status: "approved",
    rating: 4.8,
    image: "/img/Band.jpg",
    submittedAt: "2024-01-22",
  },
]
